name: academate_faculty
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.18.1
  font_awesome_flutter: ^10.5.0
  flutter_riverpod: ^2.3.6
  go_router: ^12.1.3
  file_picker: ^10.1.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  vector_math: ^2.2.0
  vm_service: ^15.0.2
  test_api: ^0.7.6
  leak_tracker: ^11.0.1
  leak_tracker_testing: ^3.0.2
  leak_tracker_flutter_testing: ^3.0.10

flutter:
  uses-material-design: true
