name: academate_faculty
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  font_awesome_flutter: ^10.8.0
  intl: ^0.19.0 
  google_fonts: ^6.1.0 
  url_launcher: ^6.2.1
  pdf: ^3.10.7
  printing: ^5.12.0
  file_picker: ^8.0.0+1

=======
  intl: ^0.20.2
>>>>>>> 14f562e52275babf1d12d68d9a2691a20dc2090f

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.1
  go_router: ^15.1.2
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.6.1
  file_picker: ^8.3.2
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  vector_math: ^2.2.0
  vm_service: ^15.0.2
  test_api: ^0.7.6
  leak_tracker: ^11.0.1
  leak_tracker_testing: ^3.0.2
  leak_tracker_flutter_testing: ^3.0.10

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
