name: academate_faculty
description: "A new Flutter project."
<<<<<<< HEAD
publish_to: 'none'
=======
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
>>>>>>> f0bfd9e00a562d3947c26e83a09e2816b0975224

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.18.1
  font_awesome_flutter: ^10.5.0
  flutter_riverpod: ^2.3.6
  go_router: ^12.1.3
  file_picker: ^10.1.9
  
=======
  intl: ^0.20.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.2.1
  go_router: ^15.1.2

>>>>>>> f0bfd9e00a562d3947c26e83a09e2816b0975224
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  vector_math: ^2.2.0
  vm_service: ^15.0.2
  test_api: ^0.7.6
  leak_tracker: ^11.0.1
  leak_tracker_testing: ^3.0.2
  leak_tracker_flutter_testing: ^3.0.10

flutter:
<<<<<<< HEAD
=======
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
>>>>>>> f0bfd9e00a562d3947c26e83a09e2816b0975224
  uses-material-design: true
